Testes
```{r}
list <- c(130,201,210,211,222,263,264,345)
scripter <- c(115,34,30,92,81)
label <- c("Teste1","Teste2")
color <- c("lightgreen","lightblue")
boxplot(list, scripter, names=label, col = color, main = "Test")
```
Limpeza e Tratamento de Dados
```{r}
dt = read.csv("tempo.csv", sep = ";", na.strings = "", stringsAsFactors = T)
head(dt,10)
summary(dt)
```
Valores Faltantes - NAs
```{r}
dt[!complete.cases(dt),]
```
Umidade - NAs
```{r}
summary(dt$Umidade)
median(dt$Umidade,na.rm = T)
dt[is.na(dt$Umidade),]$Umidade = median(dt$Umidade, na.rm = T)
median(dt$Umidade)
dt[!complete.cases(dt),]
```
Vento - NAs
```{r}
summary(dt$Vento)
dt[is.na(dt$Vento),]$Vento = "FALSO"
dt[!complete.cases(dt)]
```
Aparência fora do domínio
```{r}
summary(dt$Aparencia)
dt[dt$Aparencia == "menos",]$Aparencia = "chuva"
dt$Aparencia = factor(dt$Aparencia)
summary(dt$Aparencia)
```
Temperatura fora do domínio
```{r}
summary(dt$Temperatura)
median(dt$Temperatura)
dt[dt$Temperatura < (-130) | dt$Temperatura > 130,]
dt[is.na(dt$Temperatura),]
dt[dt$Temperatura < (-130) | dt$Temperatura > 130,]$Temperatura = median(dt$Temperatura)
summary(dt$Temperatura)
boxplot(dt$Temperatura, main = "Temperatura")
```
Umidade fora de domínio
```{r}
summary(dt$Umidade)
dt[is.na(dt$Umidade),]
dt[dt$Umidade < 0 | dt$Umidade > 100,]
median(dt$Umidade)
dt[dt$Umidade < 0 | dt$Umidade > 100,]$Umidade = median(dt$Umidade)
summary(dt$Umidade)
```
Jogar fora de domínio
```{r}
summary(dt$Jogar)
```
Final
```{r}
dt
```

